import os

from autodef import impl


@impl(debug=True)  # type: ignore[untyped-decorator]
def describe_file(path: str) -> str:
    """
    Generate a concise one-line summary of the file content at the given path.
    This should be a natural language summary of the words in the file, not basic file information.

    CRITICAL: The description MUST be generated by an internal helper function
    decorated with @llm.
    """
    return ""


def main() -> None:
    print("Running @impl with @llm example...")

    # Try to describe README.md of this project
    target_file = "README.md"
    if not os.path.exists(target_file):
        # Fallback if run from different directory
        target_file = os.path.join(os.path.dirname(__file__), "..", "README.md")

    if os.path.exists(target_file):
        try:
            print(f"Describing file: {target_file}")
            description = describe_file(target_file)
            print(f"\nFile Description:\n{description}")
        except Exception as e:
            print(f"Error: {e}")
            print(
                "\nNote: This example requires an LLM server (like LM Studio) running at http://localhost:1234/v1"
            )
    else:
        print(f"Error: Could not find {target_file}")


if __name__ == "__main__":
    main()
